@local = http://localhost:19898



#### 登录
POST {{local}}/login
Content-Type: application/json

{
  "account": "test_test",
  "password": "test_test",
  "clientType": 1
}


### 获取当前登录用户
GET {{local}}/test/user





