



#### 添加收藏书籍
POST localhost:8080/favorite/add
Content-Type: application/json

{
  "bookId": 13
}

#### 获取收藏书籍阅读进度
GET localhost:8080/user/page/get?bookId=13

### 修改收藏书籍阅读进度
POST localhost:8080/user/page/update
Content-Type: application/json

{
  "bookId": 13,
  "page": 1
}


### 获取收藏书籍列表
POST localhost:8080/favorite/list
Content-Type: application/json

{
  "page": 1,
  "pageSize": 20
}




